### ISSUE TITLE
game client options

### ISSUE THREAD

**Issue by jamesla** [jkuettner/bfbc2-server#4]
now that the game client has been patched with multiplayer removed

how do you recommend I install this game in a way that I can use this dedicated server?

ps (I own this game)

**Comment by jkuettner** [comment]
Yes, that is very sad. So far I have not had time to deal with it and I doubt that I will find a way. I hope that there will be a patch from the community.

**Comment by jamesla** [comment]
fyi origin version still multiplayer in it
